---
- name: Leaf-Spine Topology Report
  hosts: all
  connection: local
  gather_facts: false
  vars:
   - output: "{{inventory_dir}}/output"

  tasks:
    - name: Create Output Directory
      run_once: true
      file:
        path: "{{ output }}"
        state: directory

    - name: Get BGP Peers
      register: bgpsumout
      eos_command:
        provider: "{{ cli }}"
        commands: show ip bgp summary | json

    - name: Get Interface IPs
      register: intipsout
      eos_command:
        provider: "{{ cli }}"
        commands: show ip int | json

    - name: Get LLDP Neighbours
      register: lldpneiout
      eos_command:
        provider: "{{ cli }}"
        commands: show lldp neighbors | json
        
    - name: Fact Setting
      set_fact:
        bgppeers: "{{ bgpsumout.stdout[0].vrfs.default }}"
        intips: "{{ intipsout.stdout[0].interfaces }}"
        lldpnei: "{{ lldpneiout.stdout[0].lldpNeighbors }}"

    - name: Generate Device YAML File
      template:
        src: "data-yml.j2"
        dest: "{{output}}/{{inventory_hostname}}.yml"

    - name: Read in Device YAML Data
      tags:
        - reportonly
      include_vars:
        file: "{{output}}/{{inventory_hostname}}.yml"
        name: devparams

    - name: Produce Report Sections
      tags:
        - reportonly
      template:
        src: "report/report-html.j2"
        dest: "{{output}}/report-{{inventory_hostname}}.html"

    - name: Combine Report Sections
      run_once: true
      tags:
        - reportonly
      template:
        src: "report/report-html-parent.j2"
        dest: "{{output}}/report.html"
